# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad38185890b2779e5123f12368117c1592326e83fd8be7ffd9c6bc16cf3f63869f6b1d79ccbdf61159fc141f985d369168b99e791c0a67ceb912fbeff7a247f6

test:
  secret_key_base: af2521f5949b003fd8aa4ebf0a818d995903f715026809f3ed979fcdd25ce39cbd9e38938f86eec32eb3b8596f0826955c151f0524954f26d373ddfca0cd7eea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
